image: Visual Studio 2017
version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
before_build:
- dotnet restore
- choco install codecov

build_script:
- ps: >-
    cd src

    dotnet build --configuration release

    cd ../

    dotnet pack --configuration release --include-symbols -o ../nupkgs/ src
test_script:
- ps: >-
    cd test

    dotnet test /p:AltCover=true

	codecov -f "coverage.xml"
artifacts:
- path: .\nupkgs\**\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: tjJ2B5WQ2buXosN2GvPoAbkAxZlWrLwSaxzAgTpemaYQFywrr1FrqD/Wrr7rBVZA
  on:
    APPVEYOR_REPO_TAG: true
