version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: >-
    cd src/DarkSkyCore

    dotnet restore

    dotnet build


    cd ../../

    dotnet pack --configuration release -o nupkgs/ src/DarkSkyCore
test_script:
- ps: >-
    cd test/DarkSkyCore.Tests

    dotnet restore

    dotnet test
artifacts:
- path: nupkgs/
  name: nuget
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: YAF0FoHQVDwWAUmD/H8JUYkjiv4baMyRNdTaOgIw/NVMmo9IiYPq1wPOY525ubJG
  artifact: /nupkgs\/.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true