version: '{branch}-{build}'
build_script:
- ps: >-
    cd src/DarkSkyCore

    dotnet restore

    dotnet build


    cd ../../

    dotnet pack --configuration release -o nupkgs/ src/DarkSkyCore
test_script:
- ps: >-
    cd test/DarkSkyCore.Tests

    dotnet restore

    dotnet test
artifacts:
- path: nupkgs/
  name: nuget
