image: Visual Studio 2017 Preview
version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: >-
    cd src/DarkSkyCore

    dotnet restore

    dotnet build --configuration release


    cd ../../

    dotnet pack --configuration release --include-symbols -o ../../nupkgs/ src/DarkSkyCore
test_script:
- ps: >-
    cd test/DarkSkyCoreUnitTests

    dotnet restore

    dotnet test --filter "FullyQualifiedName~DarkSky.UnitTests"

    if ($env:APPVEYOR_REPO_TAG -eq $true) {
        cd ../DarkSkyCoreIntegrationTests
        dotnet restore
        dotnet test --filter "FullyQualifiedName~DarkSky.IntegrationTests"
    }
artifacts:
- path: .\nupkgs\**\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: YAF0FoHQVDwWAUmD/H8JUYkjiv4baMyRNdTaOgIw/NVMmo9IiYPq1wPOY525ubJG
  on:
    APPVEYOR_REPO_TAG: true
