image: Visual Studio 2017
version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: >-
    cd src

    dotnet restore

    dotnet build --configuration release


    cd ../

    dotnet pack --configuration release --include-symbols -o ../nupkgs/ src
test_script:
- ps: >-
    cd test

    dotnet restore

    dotnet test --filter "FullyQualifiedName~DarkSky.UnitTests"

    if ($env:APPVEYOR_REPO_TAG -eq $true -Or $env:APPVEYOR_SCHEDULED_BUILD -eq $true) {
        dotnet test --filter "FullyQualifiedName~DarkSky.IntegrationTests"
    }
artifacts:
- path: .\nupkgs\**\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: tjJ2B5WQ2buXosN2GvPoAbkAxZlWrLwSaxzAgTpemaYQFywrr1FrqD/Wrr7rBVZA
  on:
    APPVEYOR_REPO_TAG: true
